import React, { useState } from "react";
import { GetServerSideProps, GetStaticProps } from "next";
import { Category } from "../../models/Player";
import { getCategories } from "../../services/db/CategoriaService";
import { Grid, Typography } from "@mui/material";
import { normalize } from "../../services/db/PrismaClientServer";
import { TeamView, TeamCreationsView, TeamPlayer } from "../../models/Team";
import {
  autoCreateTeams,
  AutoGeneratedTeam,
} from "../../services/TeamAutoCreation";
import { fromTeamToTeamView, toTeamView } from "../../transformers/Team";
import TeamCreationButtons from "../../components/admin/TeamCreation/TeamCreationButtons";
import TeamBuildingLayout from "../../components/admin/TeamCreation/TeamBuildingLayout";
import { resetServerContext } from "react-beautiful-dnd";

interface TeamCreationProps {
  categories: Category[];
}

const ArmadoEquipos = (props: TeamCreationProps) => {
  const [players, setPlayers]: [TeamPlayer[], any] = useState([]);
  const [teamViews, setTeamViews]: [TeamView[], any] = useState([]);
  const [playersInCategories, setPlayersInCategories]: [number, any] =
    useState(0);
  const [category, setCategory]: [string, any] = useState("");

  const onClickHandler = async (event: React.MouseEvent<HTMLButtonElement>) => {
    const cat = event.currentTarget.value;
    const response = await fetch(`/api/admin/teams/${cat}`);
    const teams: TeamCreationsView = await response.json();
    const tv = teams.teams.map((el) => fromTeamToTeamView(el));
    tv.forEach((el) => {
      el.players = el.players.sort(
        (cur, next) => cur.position.value - next.position.value
      );
    });
    setCategory(cat);
    setPlayers(teams.noTeam);
    setTeamViews(tv);
    setPlayersInCategories(teams.playersInCategory);
  };

  const playerSortedHandler = (
    teams: TeamView[],
    noTeamPlayers: TeamPlayer[]
  ) => {
    teams.forEach((el) => {
      el.players = el.players.sort(
        (current, next) => current.position.value - next.position.value
      );
    });
    setTeamViews(teams);
    setPlayers(noTeamPlayers);
  };

  const saveTeamsHandler = async () => {
    const createResponse = await fetch(`/api/admin/teams/${category}`, {
      method: "POST",
      body: JSON.stringify(teamViews),
    });
  };

  return (
    <>
      <Grid container rowGap={2} mt={2}>
        <Grid item xs={12}>
          <Typography>Armado Equipos</Typography>
        </Grid>
        <Grid item xs={12}>
          <TeamCreationButtons
            clickHandler={onClickHandler}
            categories={props.categories}
          ></TeamCreationButtons>
        </Grid>
        <Grid item xs={12}>
          <TeamBuildingLayout
            noTeamPlayers={players}
            teams={teamViews}
            playersInCategory={playersInCategories}
            onPlayerRearranged={playerSortedHandler}
            saveHandler={saveTeamsHandler}
          ></TeamBuildingLayout>
        </Grid>
      </Grid>
    </>
  );
};
export const getStaticProps: GetStaticProps = async () => {
  const categories: Category[] = await getCategories("");
  resetServerContext();

  return {
    props: {
      categories: normalize(categories),
    },
  };
};

export default ArmadoEquipos;
