import { categoria, equipo, jugador, torneo } from "@prisma/client";
import { Category, Tournament, YouthPlayer } from "../models/Player";
import { Team, TeamPlayer } from "../models/Team";
import { toCategory, toPlayer, toTournament } from "./Player";
import { AutoGeneratedTeam } from "../services/TestTeamAutoCreation";

export const toTeamPlayer = (player: YouthPlayer): TeamPlayer => {
  return {
    dni: player.player?.dni || "",
    name: player.player?.name || "",
    lastName: player.player?.lastName || "",
    position: player.position,
    level: player.level,
    canBeCaptain: player.captain,
  };
};

export const toTeam = (
  team: equipo,
  category: categoria,
  tournament: torneo,
  captain?: YouthPlayer,
  players?: YouthPlayer[]
): Team => {
  const partialTeam: Team = {
    id: team.id,
    name: team.nombre,
    category: toCategory(category),
    tournament: toTournament(tournament),
    players: players?.map((el) => toTeamPlayer(el)),
  };
  if (captain) {
    partialTeam.captain = toTeamPlayer(captain);
  }
  return partialTeam;
};

export const toNewTeam = (
  autogenerated: AutoGeneratedTeam,
  category: Category,
  tournament: Tournament
): Team => {
  return {
    name: "",
    captain: autogenerated.captain || undefined,
    category,
    tournament,
  };
};
